FORMAT: 1A
HOST: http://localhost:90/

# DINA Taxonomy API

API that displays taxonomy data.

Data structures are described as MSON, see https://github.com/apiaryio/mson


# Group Taxon

## Taxon Collection [/taxon/]

### Get a Taxon [GET /taxon/{taxon_id}]

+ Parameters
    - taxon_id: 123 (number) - ID of the taxon (integer)

+ Response 200 (application/json)
    - Attributes
        - data (array[taxon])
        - meta (meta)
        - jsonapi (jsonapi)

# Data Structures

## taxon (object)

- type: taxon (string) - Type of the resource, always taxon on this endpoint
- id: 123 (string) - Identifier of the taxon
- attributes (object)
    - rubin_number: 456 (number) - Rubin number of the taxon
    - rank: species (string) - Taxonomical rank of the taxon
    - scientific_name: Mus musculus (string) - Scientific name of the taxon
    - author: Linnaeus (string) - Author of the scientific name
    - author_date: 1758 (string) - Author year of the scientif name
    - valid_name: true (boolean) - Is the name taxonomically valid
    - parent (object)
        - id: 13001537 (string) - Identifier of the parent taxon
        - scientific_name: Mus (string) - Scientif name of the parent taxon
        - rank: genus - Rank of the parent taxon
    - higherTaxa (object)
        - order: Rodentia (string)
        - suborder: Myomorpha (string)
        - infraorder: Placeholder (string)
        - superfamily: Muroidea (string)
        - family: Muridae (string)
        - subfamily: Murinae (string)
        - tribe: Placeholder (string)
        - genus: Mus (string)
        - subgenus: Mus (string)
    - vernacular_names (object)
        - en (array)
            - House Mouse (string)
            - Common Mouse (string)


## meta (object)

- source: Mammal Species of the World (string) - Source of the taxon data
- number_of_records_returned: 1 (number) - Number of records contained in the results. API may limit the maximum number of records retuned.

## jsonapi (object)

- version: 1.0 (string) - JSON-API version used