
# Use root/example as user/password credentials
version: '2'

# To rebuild:
# docker-compose up --build

services:

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./env/.env-mysql
        #ports:
        #    - 3306:3306
        volumes:
            - ./mysqldump:/docker-entrypoint-initdb.d # Directory to load SQL files to setup the database
            - mysql-slim-taxonomy:/var/lib/mysql

    backend:
        build: .
        image: dina/slim-taxonomy:0.2
        ports:
            - 90:80
#        environment: # copied from slim, what's this for?
#            docker: "true"
        volumes:
            #- ./www:/var/www
            #- vendorfiles-slim-taxonomy:/var/www/html/app/vendor
            - ./env:/var/env

volumes:
    mysql-slim-taxonomy:
    vendorfiles-slim-taxonomy:
