version: '3.1'

# Use root/example as user/password credentials
# To rebuild: docker-compose up --build
services:

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./env/.env-mysql
        volumes:
            - ./mysqldump:/docker-entrypoint-initdb.d
            - mysql-slim-taxonomy:/var/lib/mysql

    backend:
        build: .
        image: dina/slim-taxonomy:local
#        env_file:
#            - .env
        environment:
            - VIRTUAL_HOST=alpha-slimtaxonomy.dina-web.net
        ports:
            - 90:80
        volumes:
            - ./www:/var/www
            - ./env:/var/env

volumes:
    mysql-slim-taxonomy:
