
# Use root/example as user/password credentials
version: '3.1'

# To rebuild:
# docker-compose up --build

services:

    db:
        image: mysql:5.7

        # Note that if you change user/password env variables, they won't be taken into account on restart, unless you first delete the local data directory: "none of the variables below will have any effect if you start the container with a data directory that already contains a database: any pre-existing database will always be left untouched on container startup." ...and the pre-existing database is persisted on the host.
        env_file: ./env/.env-mysql
        ports:
            - 3306:3306
        volumes:
#            - ./mysqldump:/docker-entrypoint-initdb.d # Directory to load sql files from. Remember to create this dir first.
            - mysql-slim-taxonomy:/var/lib/mysql

    backend:
        build: .
        image: mikkohei13/php-slim:0.1
        ports:
            - 90:80
#        environment: # copied from slim, what's this for?
#            docker: "true"
        volumes:
            - ./www:/var/www

volumes:
    mysql-slim-taxonomy:
