version: '3'

# Use root/example as user/password credentials
# To rebuild:
# docker-compose up --build

services:

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./env/.env-mysql
        volumes:
            - ./mysqldump:/docker-entrypoint-initdb.d
            - mysql-slim-taxonomy:/var/lib/mysql

    backend:
        #build: .
        image: ${IMAGE}:${TAG}
        env_file:
            - .env
        ports:
            - 90:80
        volumes:
            - ./env:/var/env

volumes:
    mysql-slim-taxonomy:
